### PR TITLE
ses6

### PR DESCRIPTION
**Pull request by ricardoasmarques**

### CODE REVIEW

**Comment by shantur** [comment]
@ricardoasmarques,

I was really looking forward for this. Is this feature abandoned or coming as part of another change?

Thanks

**Comment by rimarques** [comment]
These changes are now included in SUSE/ceph-iscsi repo.

**Comment by ricardoasmarques** [comment]
These changes are now included in [SUSE/ceph-iscsi](https://github.com/suse/ceph-iscsi/tree/ses6-m17) repo.

**Comment by shantur** [comment]
Thanks. 👍 
Are there plans to submit this to https://github.com/ceph/ceph-iscsi ?

**Comment by ricardoasmarques** [comment]
@shantur which change in particular are you referring to?

**Comment by shantur** [comment]
@ricardoasmarques
`Adds support for kernel lio backstore`

**Comment by ricardoasmarques** [comment]
@shantur It requires SUSE kernel, so there's no plan to move it from `SUSE/ceph-iscsi` to `ceph/ceph-iscsi`.

**Comment by shantur** [comment]
@ricardoasmarques 
Thanks for clarifying that. 
Do you know what specific kernel feature is that?

**Comment by ddiss** [comment]
@shantur it's the LIO target_core_rbd functionality, which was initially proposed by Mike via:
https://www.spinics.net/lists/ceph-devel/msg25470.html

The updated/reworked source that we're using can be found in the kernel tree at:
https://kernel.opensuse.org/packages/SLE15-SP1

We're still working on getting these changes in shape for mainline kernel, but before then it doesn't make sense to merge the ceph-iscsi support upstream.

**Pull request closed without merging**
