### PR TITLE
rbd-target-api: don't ignore controls on disk create

### PR DESCRIPTION
**Pull request by trociny**

### CODE REVIEW

**Comment by trociny** [comment]
@ddiss @tserong

**Comment by ddiss** [comment]
The change appears reasonable, but looking through 15-sp5 `target_core_configfs.c` for attributes with set/enable ordering requirements similar to `emulate_legacy_capacity` I came across:
```
2798 static ssize_t target_tg_pt_gp_alua_access_state_store(struct config_item *item,  
2799                 const char *page, size_t count)                                   
2800 {                                                                                 
...                                                                  
2810         if (!target_dev_configured(dev)) {                                        
2811                 pr_err("Unable to set alua_access_state while device is"          
2812                        " not configured\n");                                      
2813                 return -ENODEV;                                                   
2814         } 

// also see pi_prot_format_store() and pi_prot_type_store()
```
i.e. There are some settings which will fail to apply until the underlying device/backstore has been enabled.
`emulate_legacy_capacity` appears to be the only attribute with inverse enable order requirements, although there are plenty of attributes which instead fail with a non-zero `dev->export_count` (i.e. device/backstore is not exposed via a transport such as iSCSI).

Will such configfs `!target_dev_configured(dev)` failures result in exceptions here? One other observation is that this `rbd-target-api.py->_disk('PUT')` codepath is shared with resize handling, which may potentially cause complications, so will need testing.

**Comment by trociny** [comment]
@ddiss Good point. If it is indeed the case it will complicate things considerably. I will do some testing.

**Comment by trociny** [comment]
I tested it, trying all controls with non-default params and it worked for all except those that did not work on "reconfigure" stage due to "not supported" error returned: 

    "emulate_write_cache to": 1
    "pi_prot_type": 1
    "pi_prot_verify": 1

I.e. these fail in my environment without my patch too. 

As for `alua_access_state`, it is not configured via `controls` and is not affected by this change.

So to me it looks like the change is safe.

**Comment by ddiss** [comment]
> I tested it, trying all controls with non-default params and it worked for all except those that did not work on "reconfigure" stage due to "not supported" error returned:
> 
> ```
> "emulate_write_cache to": 1

write-cache enablement should always fail for LIO krbd devices (`tcm_rbd_get_write_cache()` unconditionally returns `false`)

> "pi_prot_type": 1
> "pi_prot_verify": 1
> ```
> 
> I.e. these fail in my environment without my patch too.

I think this will be the `DIF protection not supported by backend` error, which is fine.

> As for `alua_access_state`, it is not configured via `controls` and is not affected by this change.
> 
> So to me it looks like the change is safe.

Great, thanks for testing this! As mentioned in https://github.com/SUSE/ceph-iscsi/pull/20#issuecomment-1451792485 , was resize also possible?

**Review by ddiss — APPROVED** [review]

**Comment by trociny** [comment]
> Great, thanks for testing this! As mentioned in #20 (comment) , was resize also possible?

Testing resize with controls is tricky. The dashboard does not make such a request. I can make it from the gwcli, but resize is sent with empty `controls` then. Anyway, I see that in the case of the resize it uses the shortcut [1] and the `add_dev_to_lio` is not called (this is where the `controls` are used). I.e. I don't expect any issues with resize.

[1] https://github.com/SUSE/ceph-iscsi/blob/master/ceph_iscsi_config/lun.py#L775

**Pull request merged**
